-- Combined migrations generated by script

-- Migration: 20260210044718_103d823a-d3f4-488e-9ca0-72c302ed17af.sql

-- Create user roles enum
CREATE TYPE public.app_role AS ENUM ('admin', 'hospital_admin', 'patient');

-- Create user roles table (separate from profiles for security)
CREATE TABLE public.user_roles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    role app_role NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UNIQUE (user_id, role)
);

-- Enable RLS on user_roles
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- Create profiles table for additional user data
CREATE TABLE public.profiles (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL UNIQUE,
    email TEXT NOT NULL,
    full_name TEXT,
    phone TEXT,
    country TEXT,
    avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS on profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Create hospitals table
CREATE TABLE public.hospitals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    country TEXT NOT NULL,
    city TEXT NOT NULL,
    address TEXT,
    description TEXT,
    logo_url TEXT,
    website_url TEXT,
    accreditations TEXT[], -- JCI, ISO, etc.
    is_verified BOOLEAN NOT NULL DEFAULT false,
    is_active BOOLEAN NOT NULL DEFAULT true,
    contact_email TEXT,
    contact_phone TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS on hospitals
ALTER TABLE public.hospitals ENABLE ROW LEVEL SECURITY;

-- Create hospital_admins table (link users to hospitals)
CREATE TABLE public.hospital_admins (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    hospital_id UUID REFERENCES public.hospitals(id) ON DELETE CASCADE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UNIQUE (user_id, hospital_id)
);

-- Enable RLS on hospital_admins
ALTER TABLE public.hospital_admins ENABLE ROW LEVEL SECURITY;

-- Create treatment categories table
CREATE TABLE public.treatment_categories (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL UNIQUE,
    slug TEXT NOT NULL UNIQUE,
    icon TEXT,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS on treatment_categories
ALTER TABLE public.treatment_categories ENABLE ROW LEVEL SECURITY;

-- Create treatments table
CREATE TABLE public.treatments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    category_id UUID REFERENCES public.treatment_categories(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS on treatments
ALTER TABLE public.treatments ENABLE ROW LEVEL SECURITY;

-- Create hospital_treatments table (pricing per hospital per treatment)
CREATE TABLE public.hospital_treatments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    hospital_id UUID REFERENCES public.hospitals(id) ON DELETE CASCADE NOT NULL,
    treatment_id UUID REFERENCES public.treatments(id) ON DELETE CASCADE NOT NULL,
    price_min NUMERIC(12,2),
    price_max NUMERIC(12,2),
    currency TEXT NOT NULL DEFAULT 'USD',
    includes TEXT[], -- What's included in the price
    duration_days INTEGER,
    notes TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UNIQUE (hospital_id, treatment_id)
);

-- Enable RLS on hospital_treatments
ALTER TABLE public.hospital_treatments ENABLE ROW LEVEL SECURITY;

-- Create leads table (questionnaire submissions)
CREATE TABLE public.leads (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT NOT NULL,
    treatment_category TEXT NOT NULL,
    urgency TEXT,
    previous_diagnosis TEXT,
    diagnosis_details TEXT,
    destination_preference TEXT[],
    budget TEXT,
    status TEXT NOT NULL DEFAULT 'new',
    assigned_to UUID REFERENCES auth.users(id),
    questionnaire_answers JSONB, -- Full answers for reference
    source TEXT DEFAULT 'website',
    utm_source TEXT,
    utm_campaign TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS on leads
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

-- Create lead_hospitals table (leads assigned to hospitals for quoting)
CREATE TABLE public.lead_hospitals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    lead_id UUID REFERENCES public.leads(id) ON DELETE CASCADE NOT NULL,
    hospital_id UUID REFERENCES public.hospitals(id) ON DELETE CASCADE NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending', -- pending, quoted, accepted, rejected
    quoted_price NUMERIC(12,2),
    currency TEXT DEFAULT 'USD',
    response_notes TEXT,
    responded_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    UNIQUE (lead_id, hospital_id)
);

-- Enable RLS on lead_hospitals
ALTER TABLE public.lead_hospitals ENABLE ROW LEVEL SECURITY;

-- Create audit_logs table for compliance
CREATE TABLE public.audit_logs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id),
    action TEXT NOT NULL,
    table_name TEXT,
    record_id UUID,
    old_values JSONB,
    new_values JSONB,
    ip_address TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS on audit_logs
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- Security definer function to check user role (avoids RLS recursion)
CREATE OR REPLACE FUNCTION public.has_role(_user_id UUID, _role app_role)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.user_roles
    WHERE user_id = _user_id
      AND role = _role
  )
$$;

-- Function to get hospital IDs for a user
CREATE OR REPLACE FUNCTION public.get_user_hospital_ids(_user_id UUID)
RETURNS SETOF UUID
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT hospital_id FROM public.hospital_admins WHERE user_id = _user_id
$$;

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;

-- Create triggers for updated_at
CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_hospitals_updated_at BEFORE UPDATE ON public.hospitals FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_hospital_treatments_updated_at BEFORE UPDATE ON public.hospital_treatments FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_leads_updated_at BEFORE UPDATE ON public.leads FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TRIGGER update_lead_hospitals_updated_at BEFORE UPDATE ON public.lead_hospitals FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Auto-create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (user_id, email)
  VALUES (NEW.id, NEW.email);
  
  -- Default new users to patient role
  INSERT INTO public.user_roles (user_id, role)
  VALUES (NEW.id, 'patient');
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Trigger for new user signup
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- RLS Policies

-- User Roles: Users can view their own roles, admins can view all
CREATE POLICY "Users can view own roles" ON public.user_roles
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Admins can manage all roles" ON public.user_roles
  FOR ALL USING (public.has_role(auth.uid(), 'admin'));

-- Profiles: Users can manage their own profile
CREATE POLICY "Users can view own profile" ON public.profiles
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can update own profile" ON public.profiles
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Admins can view all profiles" ON public.profiles
  FOR SELECT USING (public.has_role(auth.uid(), 'admin'));

-- Hospitals: Public read for verified hospitals, admin full access
CREATE POLICY "Anyone can view verified hospitals" ON public.hospitals
  FOR SELECT USING (is_verified = true AND is_active = true);

CREATE POLICY "Admins can manage hospitals" ON public.hospitals
  FOR ALL USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Hospital admins can update their hospital" ON public.hospitals
  FOR UPDATE USING (id IN (SELECT public.get_user_hospital_ids(auth.uid())));

-- Hospital Admins: Admin only
CREATE POLICY "Admins can manage hospital admins" ON public.hospital_admins
  FOR ALL USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Hospital admins can view their assignments" ON public.hospital_admins
  FOR SELECT USING (user_id = auth.uid());

-- Treatment Categories: Public read, admin write
CREATE POLICY "Anyone can view treatment categories" ON public.treatment_categories
  FOR SELECT USING (true);

CREATE POLICY "Admins can manage treatment categories" ON public.treatment_categories
  FOR ALL USING (public.has_role(auth.uid(), 'admin'));

-- Treatments: Public read, admin write
CREATE POLICY "Anyone can view treatments" ON public.treatments
  FOR SELECT USING (is_active = true);

CREATE POLICY "Admins can manage treatments" ON public.treatments
  FOR ALL USING (public.has_role(auth.uid(), 'admin'));

-- Hospital Treatments: Public read for active, hospital/admin can manage
CREATE POLICY "Anyone can view active hospital treatments" ON public.hospital_treatments
  FOR SELECT USING (is_active = true);

CREATE POLICY "Admins can manage hospital treatments" ON public.hospital_treatments
  FOR ALL USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Hospital admins can manage their treatments" ON public.hospital_treatments
  FOR ALL USING (hospital_id IN (SELECT public.get_user_hospital_ids(auth.uid())));

-- Leads: Public insert (anonymous), admin/assigned user can view
CREATE POLICY "Anyone can create leads" ON public.leads
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Admins can manage all leads" ON public.leads
  FOR ALL USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Assigned users can view their leads" ON public.leads
  FOR SELECT USING (assigned_to = auth.uid());

-- Lead Hospitals: Admin and hospital admins for their hospitals
CREATE POLICY "Admins can manage lead hospitals" ON public.lead_hospitals
  FOR ALL USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Hospital admins can view their lead assignments" ON public.lead_hospitals
  FOR SELECT USING (hospital_id IN (SELECT public.get_user_hospital_ids(auth.uid())));

CREATE POLICY "Hospital admins can update their responses" ON public.lead_hospitals
  FOR UPDATE USING (hospital_id IN (SELECT public.get_user_hospital_ids(auth.uid())));

-- Audit Logs: Admin only
CREATE POLICY "Admins can view audit logs" ON public.audit_logs
  FOR SELECT USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "System can insert audit logs" ON public.audit_logs
  FOR INSERT WITH CHECK (true);

-- Insert default treatment categories
INSERT INTO public.treatment_categories (name, slug, icon, description) VALUES
  ('Cardiac Surgery', 'cardiac', '🫀', 'Heart and cardiovascular procedures'),
  ('Orthopedics', 'orthopedics', '🦴', 'Joint replacement, spine surgery, and bone procedures'),
  ('Ophthalmology', 'ophthalmology', '👁️', 'Eye surgery including LASIK and cataract removal'),
  ('Dental Care', 'dental', '🦷', 'Dental implants, veneers, and oral surgery'),
  ('Fertility', 'fertility', '👶', 'IVF, IUI, and reproductive treatments'),
  ('Neurology', 'neurology', '🧠', 'Brain and nervous system procedures'),
  ('Cosmetic Surgery', 'cosmetic', '💆', 'Plastic and reconstructive surgery'),
  ('Other', 'other', '🏥', 'Other medical treatments');


-- Migration: 20260210044746_7d744221-95e0-4e99-8b05-35bb98c173d7.sql

-- Tighten audit_logs insert: only authenticated users or service role
DROP POLICY "System can insert audit logs" ON public.audit_logs;
CREATE POLICY "Authenticated users can insert audit logs" ON public.audit_logs
  FOR INSERT TO authenticated WITH CHECK (user_id = auth.uid());

-- The "Anyone can create leads" policy stays WITH CHECK (true) intentionally
-- because anonymous website visitors must be able to submit questionnaire leads


-- Migration: 20260210050000_create_testimonials_table.sql

-- Create testimonials table and seed defaults
CREATE TABLE public.testimonials (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  country TEXT,
  treatment TEXT,
  quote TEXT NOT NULL,
  rating INTEGER NOT NULL DEFAULT 5,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read testimonials
CREATE POLICY "Anyone can view testimonials" ON public.testimonials
  FOR SELECT USING (true);

-- Allow anyone (anonymous) to insert testimonials (for public submissions)
CREATE POLICY "Anyone can create testimonials" ON public.testimonials
  FOR INSERT WITH CHECK (true);

-- Seed default testimonials
INSERT INTO public.testimonials (name, country, treatment, quote, rating) VALUES
  ('Sarah M.', 'United States', 'Dental Implants', 'I saved over $12,000 on dental implants in Turkey. The hospital was more modern than anything back home, and the care was exceptional.', 5),
  ('James L.', 'United Kingdom', 'Hip Replacement', 'After 18 months on the NHS waiting list, I had my hip replaced in India within 2 weeks. Best decision I ever made.', 5),
  ('Maria K.', 'Canada', 'IVF Treatment', 'We went through 2 failed IVF cycles at home. Our third attempt in Spain was successful — and cost a fraction of what we had paid before.', 5);


-- Migration: 20260210051000_add_email_to_testimonials.sql

-- Add email column to testimonials
ALTER TABLE public.testimonials ADD COLUMN IF NOT EXISTS email TEXT;


-- Migration: 20260210060000_add_category_assets_and_seed.sql

-- Add color/icon/image fields to treatment_categories and seed categories + treatments

ALTER TABLE public.treatment_categories
  ADD COLUMN IF NOT EXISTS color TEXT,
  ADD COLUMN IF NOT EXISTS bg_color TEXT,
  ADD COLUMN IF NOT EXISTS image_url TEXT;

-- Seed categories (insert or ignore existing by slug)
INSERT INTO public.treatment_categories (id, name, slug, icon, description, color, bg_color, image_url)
VALUES
  (gen_random_uuid(), 'Cardiac Surgery', 'cardiac', '🫀', 'Heart and cardiovascular procedures', '#ff3b30', 'rgba(255,59,48,0.08)', 'https://images.example.com/cardiac.jpg'),
  (gen_random_uuid(), 'Orthopedics', 'orthopedics', '🦴', 'Joint replacement, spine surgery, and bone procedures', '#ff9500', 'rgba(255,149,0,0.08)', 'https://images.example.com/orthopedics.jpg'),
  (gen_random_uuid(), 'Ophthalmology', 'ophthalmology', '👁️', 'Eye surgery including LASIK and cataract removal', '#34c759', 'rgba(52,199,89,0.08)', 'https://images.example.com/ophthalmology.jpg'),
  (gen_random_uuid(), 'Dental Care', 'dental', '🦷', 'Dental implants, veneers, and oral surgery', '#ffd60a', 'rgba(255,214,10,0.08)', 'https://images.example.com/dental.jpg'),
  (gen_random_uuid(), 'Fertility', 'fertility', '👶', 'IVF, IUI, and reproductive treatments', '#ff2d55', 'rgba(255,45,85,0.08)', 'https://images.example.com/fertility.jpg'),
  (gen_random_uuid(), 'Neurology', 'neurology', '🧠', 'Brain and nervous system procedures', '#5ac8fa', 'rgba(90,200,250,0.08)', 'https://images.example.com/neurology.jpg')
ON CONFLICT (slug) DO NOTHING;

-- Insert sample treatments linked to categories (use slug lookups)
INSERT INTO public.treatments (id, category_id, name, description, is_active)
VALUES
  (gen_random_uuid(), (SELECT id FROM public.treatment_categories WHERE slug='cardiac' LIMIT 1), 'Coronary Artery Bypass Grafting (CABG)', 'CABG description...', true),
  (gen_random_uuid(), (SELECT id FROM public.treatment_categories WHERE slug='orthopedics' LIMIT 1), 'Total Hip Replacement', 'Hip replacement description...', true),
  (gen_random_uuid(), (SELECT id FROM public.treatment_categories WHERE slug='ophthalmology' LIMIT 1), 'Cataract Surgery', 'Cataract surgery description...', true),
  (gen_random_uuid(), (SELECT id FROM public.treatment_categories WHERE slug='dental' LIMIT 1), 'Dental Implants', 'Dental implants description...', true),
  (gen_random_uuid(), (SELECT id FROM public.treatment_categories WHERE slug='fertility' LIMIT 1), 'IVF Cycle', 'IVF description...', true),
  (gen_random_uuid(), (SELECT id FROM public.treatment_categories WHERE slug='neurology' LIMIT 1), 'Deep Brain Stimulation', 'DBS description...', true)
ON CONFLICT DO NOTHING;

-- Allow patients to view leads matching their email via profiles
CREATE POLICY "Patients can view leads by email"
ON public.leads
FOR SELECT
USING (
  email IN (
    SELECT p.email FROM public.profiles p WHERE p.user_id = auth.uid()
  )
);

-- Allow patients to withdraw (update status) their own leads
CREATE POLICY "Patients can update own leads"
ON public.leads
FOR UPDATE
USING (
  email IN (
    SELECT p.email FROM public.profiles p WHERE p.user_id = auth.uid()
  )
)
WITH CHECK (
  email IN (
    SELECT p.email FROM public.profiles p WHERE p.user_id = auth.uid()
  )
);

ALTER TABLE public.leads
  ADD COLUMN IF NOT EXISTS mobile TEXT;